const CATEGORIES=['Vivienda','Alimentación','Transporte','Salud','Educación','Servicios','Deudas','Ahorro e inversión','Entretenimiento','Cuidado personal','Mascotas','Familia','Impuestos','Otros gastos'];
const CATEGORY_OPTIONS={
 'Ingreso':['Sueldo','Ingresos extra','Venta','Reembolso','Otros ingresos'],
 'Gasto':CATEGORIES,
 'Ahorro':['Fondo de emergencia','Meta de ahorro','Ahorro e inversión'],
 'Pago de deuda':['Deudas']
};
const today=new Date();const iso=d=>d.toISOString().slice(0,10);const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n)||0);
const seed={transactions:[
 {id:1,date:iso(new Date(today.getFullYear(),today.getMonth(),1)),type:'Ingreso',category:'Otros gastos',description:'Ingreso quincenal',amount:6300,notes:''},
 {id:2,date:iso(new Date(today.getFullYear(),today.getMonth(),3)),type:'Gasto',category:'Alimentación',description:'Supermercado',amount:840,notes:''},
 {id:3,date:iso(new Date(today.getFullYear(),today.getMonth(),5)),type:'Gasto',category:'Mascotas',description:'Alimento de Dobby',amount:720,notes:''},
 {id:4,date:iso(new Date(today.getFullYear(),today.getMonth(),7)),type:'Ahorro',category:'Ahorro e inversión',description:'Fondo de emergencia',amount:500,notes:''},
 {id:5,date:iso(new Date(today.getFullYear(),today.getMonth(),9)),type:'Pago de deuda',category:'Deudas',description:'Pago tarjeta ejemplo',amount:600,debtId:1,notes:''}
],debts:[{id:1,name:'Tarjeta ejemplo',initial:5000,minimum:500,dueDate:iso(new Date(today.getFullYear(),today.getMonth(),25))}],budgets:{Alimentación:2500,Transporte:1400,Servicios:1800,Mascotas:1200,Entretenimiento:900,Deudas:1800},demo:true};
let state=load();let periodMode='month';
function load(){try{return JSON.parse(localStorage.getItem('ferli-finanzas'))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem('ferli-finanzas',JSON.stringify(state));renderAll()}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function selectedDate(){const v=document.querySelector('#periodPicker').value;return v?new Date(v+'-01T12:00:00'):today}
function inPeriod(t){const d=new Date(t.date+'T12:00:00'),p=selectedDate();if(periodMode==='month')return d.getMonth()===p.getMonth()&&d.getFullYear()===p.getFullYear();const day=(p.getDay()+6)%7,start=new Date(p);start.setDate(p.getDate()-day);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(start.getDate()+7);return d>=start&&d<end}
function totals(list=state.transactions.filter(inPeriod)){const sum=type=>list.filter(x=>x.type===type).reduce((a,x)=>a+Number(x.amount),0);const income=sum('Ingreso'),expense=sum('Gasto'),saving=sum('Ahorro'),debt=sum('Pago de deuda');return{income,expense,saving,debt,flow:income-expense-saving-debt}}
function renderDashboard(){const t=totals();document.querySelector('#summaryCards').innerHTML=[['Ingresos',t.income,'positive'],['Gastos',t.expense,''],['Ahorro',t.saving,''],['Disponible',t.flow,t.flow<0?'negative':'positive']].map(([l,v,c])=>`<div class="card ${c}"><small>${l}</small><strong>${money(v)}</strong><small>${periodMode==='month'?'Periodo mensual':'Semana seleccionada'}</small></div>`).join('');const expenses=state.transactions.filter(x=>inPeriod(x)&&x.type==='Gasto'),by={};expenses.forEach(x=>by[x.category]=(by[x.category]||0)+Number(x.amount));const max=Math.max(1,...Object.values(by));document.querySelector('#spentTotal').textContent=money(t.expense);document.querySelector('#categoryBars').innerHTML=Object.entries(by).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div><div class="bar-head"><span>${esc(k)}</span><strong>${money(v)}</strong></div><div class="track"><i style="width:${v/max*100}%"></i></div></div>`).join('')||'<div class="empty">Aún no hay gastos en este periodo.</div>';document.querySelector('#recentList').innerHTML=transactionRows([...state.transactions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5))}
function transactionRows(items){return items.map(x=>`<div class="row"><div class="badge">${x.type==='Ingreso'?'＋':x.type==='Pago de deuda'?'✓':'−'}</div><div><div class="row-title">${esc(x.description)}</div><button type="button" class="text-button" data-edit-movement="${x.id}">Editar</button><div class="row-sub">${esc(x.category)} · ${x.date.split('-').reverse().join('/')}</div></div><div class="amount ${x.type==='Ingreso'?'income':'expense'}">${x.type==='Ingreso'?'+':'−'}${money(x.amount)}</div></div>`).join('')||'<div class="empty">No hay movimientos.</div>'}
function renderMovements(){const type=document.querySelector('#typeFilter').value,q=document.querySelector('#searchInput').value.toLowerCase();const list=[...state.transactions].filter(x=>(!type||x.type===type)&&(!q||`${x.description} ${x.category}`.toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date));document.querySelector('#movementList').innerHTML=transactionRows(list)}
function debtPaid(id){return Number(state.debts.find(d=>Number(d.id)===Number(id))?.previousPaid||0)+ state.transactions.filter(x=>x.type==='Pago de deuda'&&Number(x.debtId)===Number(id)).reduce((a,x)=>a+Number(x.amount),0)}
function renderDebts(){document.querySelector('#debtCards').innerHTML=state.debts.map(d=>{const paid=debtPaid(d.id),left=Math.max(0,d.initial-paid),pct=Math.min(100,paid/Math.max(0.01,d.initial)*100);return`<article class="panel debt-card"><div class="debt-top"><div><span class="eyebrow">${pct.toFixed(0)}% liquidado</span><h3>${esc(d.name)}</h3></div><strong>${money(left)}</strong></div><div class="progress"><i style="width:${pct}%"></i></div><div class="debt-meta"><span>Inicial ${money(d.initial)}</span><span>Pagado ${money(paid)}</span></div><div class="debt-meta"><span>Mínimo ${money(d.minimum)}</span><span>Límite ${d.dueDate||'Sin fecha'}</span></div><p>Pagado antes de usar la app: ${money(d.previousPaid||0)}</p><div class="button-stack"><button class="secondary" data-edit-debt="${d.id}">Editar deuda</button><button class="primary" data-pay-debt="${d.id}">Aplicar pago</button></div><details><summary>Historial de pagos</summary>${transactionRows(state.transactions.filter(x=>x.type==='Pago de deuda'&&Number(x.debtId)===Number(d.id)))}</details></article>`}).join('')||'<div class="panel empty">Agrega tu primera deuda.</div>'}
function renderBudget(){const expenses=state.transactions.filter(x=>inPeriod(x)&&x.type==='Gasto');document.querySelector('#budgetList').innerHTML=CATEGORIES.map(c=>{const spent=expenses.filter(x=>x.category===c).reduce((a,x)=>a+Number(x.amount),0),budget=Number(state.budgets[c]||0),pct=budget?Math.min(100,spent/budget*100):0;return`<div class="budget-item"><div class="budget-line"><div><strong>${c}</strong><div class="row-sub">Gastado ${money(spent)} · Disponible ${money(Math.max(0,budget-spent))}</div></div><input aria-label="Presupuesto ${c}" data-budget="${c}" type="number" min="0" step="50" value="${budget}"></div><div class="progress"><i style="width:${pct}%;background:${spent>budget&&budget?'#b64b54':'#4d8f75'}"></i></div></div>`}).join('')}
function renderAll(){renderDashboard();renderMovements();renderDebts();renderBudget();fillDebtOptions()}
function go(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo({top:0,behavior:'smooth'})}
function toast(s){const t=document.querySelector('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function fillDebtOptions(){document.querySelector('[name="debtId"]').innerHTML='<option value="">Selecciona una deuda</option>'+state.debts.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}
function fillCategoryOptions(){const select=document.querySelector('[name="category"]'),current=select.value,items=CATEGORY_OPTIONS[typeSelect.value]||CATEGORIES;select.innerHTML='<option value="">Selecciona una categoría</option>'+items.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');if(items.includes(current))select.value=current}
document.querySelector('#periodPicker').value=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}`;
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{periodMode=b.dataset.period;document.querySelectorAll('[data-period]').forEach(x=>x.classList.toggle('active',x===b));renderAll()});document.querySelector('#periodPicker').onchange=renderAll;
document.querySelector('#typeFilter').onchange=renderMovements;document.querySelector('#searchInput').oninput=renderMovements;
let editingMovement=null,editingDebt=null;
const transactionForm=document.querySelector('#transactionForm'),debtForm=document.querySelector('#debtForm');
debtForm.querySelector('[name="initial"]').closest('label').firstChild.textContent='Monto original de la deuda';
debtForm.querySelector('[name="initial"]').closest('label').insertAdjacentHTML('afterend','<label>Pagado antes de usar la app<input name="previousPaid" type="number" min="0" step="0.01" value="0" required></label><p>Captura el total que ya habías abonado. No se contará como gasto nuevo. Los pagos registrados en la app se suman automáticamente.</p>');
const typeSelect=document.querySelector('[name="type"]');typeSelect.onchange=()=>{document.querySelector('.debt-field').classList.toggle('hidden',typeSelect.value!=='Pago de deuda');fillCategoryOptions()};fillCategoryOptions();
function openMovement(id=null,debtId=null){
 editingMovement=id;transactionForm.reset();fillDebtOptions();
 const obj=state.transactions.find(x=>String(x.id)===String(id));
 transactionForm.querySelector('h2').textContent=obj?'Editar movimiento':'Agregar movimiento';
 typeSelect.value=obj?.type||(debtId?'Pago de deuda':'Gasto');typeSelect.onchange();
 if(obj){for(const [key,value] of Object.entries(obj)){const field=transactionForm.elements.namedItem(key);if(field)field.value=value}}
 else{transactionForm.elements.date.value=iso(new Date());if(debtId){transactionForm.elements.debtId.value=debtId;transactionForm.elements.category.value='Deudas';transactionForm.elements.description.value='Pago '+state.debts.find(d=>String(d.id)===String(debtId)).name}}
 document.querySelector('#transactionDialog').showModal();
}
function openDebt(id=null){editingDebt=id;debtForm.reset();const obj=state.debts.find(d=>String(d.id)===String(id));debtForm.querySelector('h2').textContent=obj?'Editar deuda':'Agregar deuda';if(obj){for(const [key,value] of Object.entries(obj)){const field=debtForm.elements.namedItem(key);if(field)field.value=value}}document.querySelector('#debtDialog').showModal()}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>b.dataset.open==='transaction'?openMovement():openDebt());
document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.editMovement)openMovement(b.dataset.editMovement);if(b.dataset.editDebt)openDebt(b.dataset.editDebt);if(b.dataset.payDebt)openMovement(null,b.dataset.payDebt)});
transactionForm.onsubmit=e=>{
 e.preventDefault();const obj=Object.fromEntries(new FormData(transactionForm));obj.amount=Number(obj.amount);
 if(!Number.isFinite(obj.amount)||obj.amount<=0){toast('Ingresa un monto mayor que cero');return}
 if(obj.type==='Pago de deuda'){
 const debt=state.debts.find(d=>String(d.id)===String(obj.debtId));if(!debt){toast('Selecciona la deuda asociada');return}
 const other=state.transactions.filter(x=>x.type==='Pago de deuda'&&String(x.debtId)===String(debt.id)&&String(x.id)!==String(editingMovement)).reduce((sum,x)=>sum+Number(x.amount),0);
 if(Number(debt.previousPaid||0)+other+obj.amount>Number(debt.initial)+0.001){toast('El pago supera el saldo pendiente');return}
 }else{delete obj.debtId}
 const index=state.transactions.findIndex(x=>String(x.id)===String(editingMovement));obj.id=index>=0?state.transactions[index].id:Date.now();if(index>=0)state.transactions[index]={...state.transactions[index],...obj};else state.transactions.push(obj);
 state.demo=false;save();transactionForm.closest('dialog').close();toast('Movimiento guardado');
};
debtForm.onsubmit=e=>{
 e.preventDefault();const obj=Object.fromEntries(new FormData(debtForm));for(const key of ['initial','minimum','previousPaid'])obj[key]=Number(obj[key]);
 if(!Number.isFinite(obj.initial)||obj.initial<=0||!Number.isFinite(obj.previousPaid)||obj.previousPaid<0||!Number.isFinite(obj.minimum)||obj.minimum<0){toast('Revisa los montos de la deuda');return}
 const payments=state.transactions.filter(x=>x.type==='Pago de deuda'&&String(x.debtId)===String(editingDebt)).reduce((sum,x)=>sum+Number(x.amount),0);
 if(obj.previousPaid+payments>obj.initial+0.001){toast('El total pagado supera el monto original');return}
 const index=state.debts.findIndex(d=>String(d.id)===String(editingDebt));obj.id=index>=0?state.debts[index].id:Date.now();if(index>=0)state.debts[index]={...state.debts[index],...obj};else state.debts.push(obj);
 state.demo=false;save();debtForm.closest('dialog').close();toast('Deuda guardada');
};
document.querySelector('#budgetList').onchange=e=>{if(e.target.dataset.budget){state.budgets[e.target.dataset.budget]=Number(e.target.value);state.demo=false;save()}};
document.querySelector('#clearDemo').onclick=()=>{if(confirm('¿Quieres borrar los datos de ejemplo y comenzar en blanco?')){state={transactions:[],debts:[],budgets:{},demo:false};save();toast('Listo para comenzar')}};
document.querySelector('#importBtn').onclick=()=>document.querySelector('#importFile').click();document.querySelector('#importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.name.endsWith('.json')){state=JSON.parse(await file.text());save();toast('Respaldo importado');return}if(!window.XLSX)throw new Error('Necesitas conexión a internet para importar Excel por primera vez.');const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const pick=n=>wb.SheetNames.find(s=>s.toLowerCase().includes(n));const ms=pick('movimiento');if(ms){const rows=XLSX.utils.sheet_to_json(wb.Sheets[ms],{defval:''});state.transactions=rows.map((r,i)=>({id:Date.now()+i,date:excelDate(r.Fecha||r.fecha),type:r.Tipo||r.tipo||'Gasto',category:r.Categoría||r.Categoria||r.category||'Otros gastos',description:r.Descripción||r.Descripcion||r.description||'Movimiento importado',amount:Number(r.Monto||r.monto||r.amount||0),notes:r.Notas||'',debtId:r['Deuda asociada']||''})).filter(x=>x.amount)}const ds=pick('deuda');if(ds){const rows=XLSX.utils.sheet_to_json(wb.Sheets[ds],{defval:''});state.debts=rows.map((r,i)=>({id:r['ID deuda']||Date.now()+5000+i,previousPaid:Number(r['Pagado antes de la app']||0),name:r.Deuda||r.Nombre||'Deuda importada',initial:Number(r['Saldo histórico (inicial)']||r['Saldo histórico']||r['Saldo inicial']||0),minimum:Number(r['Pago mínimo']||0),dueDate:excelDate(r['Fecha límite'])})).filter(x=>x.initial)}state.demo=false;save();toast('Excel importado')}catch(err){alert(err.message)}finally{e.target.value=''}};
function excelDate(v){if(!v)return iso(today);if(v instanceof Date)return iso(v);if(typeof v==='number'){const d=new Date((v-25569)*86400*1000);return iso(d)}const d=new Date(v);return isNaN(d)?iso(today):iso(d)}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.querySelector('#exportBackup').onclick=()=>download('Ferli_Finanzas_respaldo.json',JSON.stringify(state,null,2),'application/json');
document.querySelector('#exportExcel').onclick=()=>{const xml=spreadsheetXml();download('Ferli_Finanzas.xls',xml,'application/vnd.ms-excel');toast('Excel descargado')};
function cell(v,type='String'){const safe=esc(v);return`<Cell><Data ss:Type="${type}">${safe}</Data></Cell>`}function row(vals){return`<Row>${vals.map(v=>cell(v[0],v[1])).join('')}</Row>`}function sheetXml(name,headers,rows){return`<Worksheet ss:Name="${name}"><Table>${row(headers.map(x=>[x]))}${rows.map(row).join('')}</Table></Worksheet>`}
function spreadsheetXml(){const movements=state.transactions.map(x=>[[x.date],[x.type],[x.category],[x.description],[Number(x.amount),'Number'],[x.notes||''],[x.debtId||'']]);const debts=state.debts.map(d=>{const paid=debtPaid(d.id);return[[d.name],[Number(d.initial),'Number'],[Number(d.minimum),'Number'],[paid,'Number'],[Math.max(0,d.initial-paid),'Number'],[d.dueDate||''],[d.id],[Number(d.previousPaid||0),'Number']]});const budgets=Object.entries(state.budgets).map(([k,v])=>[[k],[Number(v),'Number']]);return`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">${sheetXml('Movimientos',['Fecha','Tipo','Categoría','Descripción','Monto','Notas','Deuda asociada'],movements)}${sheetXml('Deudas',['Deuda','Saldo inicial','Pago mínimo','Pagado acumulado','Saldo por pagar','Fecha límite','ID deuda','Pagado antes de la app'],debts)}${sheetXml('Presupuesto',['Categoría','Presupuesto mensual'],budgets)}</Workbook>`}
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.querySelector('#installBtn').classList.remove('hidden')});document.querySelector('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');renderAll();
